[package]
name = "invisible-char-detector"
version = "1.0.0"
edition = "2021"
authors = ["nealhar"]
description = "Detects hidden Unicode characters and Trojan Source attacks."

[dependencies]
glob = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"